# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zachary Sparrow
masthead_title: " "
logo: "/assets/images/zs_logo_recolored.svg"
email: zacharysparrow95@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio for Zachary Sparrow
#twitter_username: username
github_username: zacharysparrow
minimal_mistakes_skin: "dirt" #default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
lunr:
  search_within_pages: true
search_full_content: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Zachary Sparrow, Ph.D."
  avatar : "/assets/images/github-profile.jpg"
  bio    : "Postdoctoral scientist looking for data-driven insight into chemical physics."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zacharysparrow@cornell.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zach-sparrow/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zacharysparrow"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zacharysparrow@cornell.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zach-sparrow/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zacharysparrow"
atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: misc
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  - scope:
      path: ""
      type: splash
    values:
      layout: splash
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  misc:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/


# category_archive:
#  type: liquid
#  path: /categories/
# tag_archive:
#  type: liquid
#  path: /tags/
